Revert "Add API and TEST_API variables"
This reverts commit 615ba089510de52d0aaf285088745c27c4b08b8c.

Reason for revert: Speculatively reverting for https://crbug.com/449097954

>  AttributeError: module 'RECIPE_MODULES.build.chromium_swarming' has no attribute 'SwarmingTask'

Original change's description:
> Add API and TEST_API variables
>
> Eventually these will be required.
>
> Bug: b/446916327
> Change-Id: Ic1f218b46a5a65afe82f726d5af48974c4d028b2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/6978256
> Commit-Queue: Garrett Beaty <gbeaty@google.com>
> Auto-Submit: Rob Mohr <mohrr@google.com>
> Reviewed-by: Garrett Beaty <gbeaty@google.com>

Bug: b/446916327, b/449097954
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I82db5df283760f27a3cc4055a4879c060bcee33e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/7008068
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Junji Watanabe <jwata@google.com>