Handle ExpansionLoc with no file path
I ran into the following error running tricium_clang_tidy_script.py
against v8:

Traceback (most recent call last):
  File ".../recipes/recipe_modules/tricium_clang_tidy/resources/tricium_clang_tidy_script.py", line 1633, in <module>
    sys.exit(main())
  File ".../recipes/recipe_modules/tricium_clang_tidy/resources/tricium_clang_tidy_script.py", line 1620, in main
    results = _convert_tidy_output_json_obj(base_path, tidy_actions,
  File ".../recipes/recipe_modules/tricium_clang_tidy/resources/tricium_clang_tidy_script.py", line 1423, in _convert_tidy_output_json_obj
    expansion_locs=normalize_expansion_locs(note.expansion_locs),
  File ".../recipes/recipe_modules/tricium_clang_tidy/resources/tricium_clang_tidy_script.py", line 1387, in normalize_expansion_locs
    n = _normalize_path_to_base(loc.file_path, base_path)
  File ".../recipes/recipe_modules/tricium_clang_tidy/resources/tricium_clang_tidy_script.py", line 1298, in _normalize_path_to_base
    assert os.path.isabs(path), '%s should be absolute' % path
AssertionError:  should be absolute

It corresponded to the following TidyNote:

_TidyNote(file_path='/.../chromium/src/v8/src/common/globals.h',
          line_number=786,
          message='make conversion explicit to silence this warning',
          expansion_locs=(_ExpandedFrom(file_path='', line_number=1),))

Updating the script to handle that case.

Also adding a log message for how many clang-tidy jobs will be used. By
default it invokes one clang tidy instance per CPU core, but that seems
to bring down my Cloudtop (which has 96 cores). I'm not sure of a good
way to handle that, but at least adding a log message makes it easier to
know what is happening behind the scenes.

Bug: None
Change-Id: I65a4cab0e53dd068b0a2d6efaf095d0ab3be67c6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/7661309
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Junji Watanabe <jwata@google.com>
Commit-Queue: Andrew Williams <awillia@chromium.org>