Fix recipe error messages when OS dimension is missing in chrome tests
Right now the error message is confusingly:
  File "/usr/local/google/code/clankium2/src/tools/utr/.bundles/chromium/build/recipes/recipe_modules/chromium_swarming/api.py", line 1930, in task_name
    return '%s/%s/%s%s' % (self.request.name, self.request[0].dimensions['os'],

This should make it look like:
  File "/usr/local/google/home/bpastene/build/bundle/build/recipes/recipe_modules/chromium_swarming/api.py", line 672, in trigger_task
    assert 'os' in task.request[0].dimensions, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: All tasks must have an os dimension: {'cpu': 'x86-64', 'pool': 'chromium.tests'}

This also fixes the UTR to instead of removing a dimension by
emplacing a val of None, it just removes it all together from the test
spec's dimensions map.

Bug: 386167803
Change-Id: Ic88994cd3a54bf3aa49d7723a883520eff7ea3b3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/7465919
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Struan Shrimpton <sshrimp@google.com>