utr: Make build_dir path absolute when using the default
When using the default build dir to compile, the recipe will fail
with errors like:
AssertionError: out/Release/args.gn is not absolute

So this absolute-izes it by joining with the absolute checkout path.
Every bot uses a build dir in the checkout, so this should be fine.

Bug: 41492686
Change-Id: I0a405cd146af626db8c32bf7afbda25fbdc86d7d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/5342419
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Struan Shrimpton <sshrimp@google.com>