Revert "Add logic to measure chrome build time"
This reverts commit b39f37365e1ae3cb8a0abcf6fab422a4bfcb511b.

Reason for revert: 
https://ci.chromium.org/ui/p/chromium/builders/build/linux-build-perf-no-rbe/256/overview

FileNotFoundError: [Errno 2] No such file or directory: "(/usr/bin/time -v ['/b/s/w/ir/cache/builder/src/third_party/ninja/ninja', '-C', '/b/s/w/ir/cache/builder/src/out/Release', 'chrome']) 2>/b/s/w/ir/cache/resource_usage/time_log.txt"


Original change's description:
> Add logic to measure chrome build time
>
> Invokes /usr/bin/time to collect resource usage stats.
>
> Bug: b/333389736
> Change-Id: I7ff7df7e7ca3a33b5df545094b19a5916a3bdda1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/5480487
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Commit-Queue: Prakhar Asthana <pasthana@google.com>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>

Bug: b/333389736
Change-Id: I5c8ecd6fafb4f0a77c37d2438e85f6b352b92f4b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/5492799
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Junji Watanabe <jwata@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>