daemonizer: Fix opening unbuffered /dev/null
In daemonizer.py we open unbuffered /dev/null for writing:

> se = open(os.devnull, 'a+', 0)

Shortly after that stderr is redirected to |se|. Unfortunately, with
Python 3 the above causes an error:

> ValueError: can't have unbuffered text I/O

I am not sure why we wanted exactly unbuffered stderr and kept the
stdout buffered. The code appears in this form straight from 2013.
Perhaps some code checks the buffering somehow? This sounds rather
unlikely, especially because this variable |se| soon goes out of scope
having only participated in one operation:

> os.dup2(se.fileno(), sys.stderr.fileno())

I believe the os.dup2 does not extract any information about the file
being buffered or any info about its Python treatment for binary files.
So both fixes would work:

1. se = open(os.devnull, 'ab+', 0)
2. se = open(os.devnull, 'a+')

Choosing (2) for consistency with the previous line.

Bug: 1478244
Change-Id: If791c7d8de0d5bcfad54d9e7a8c2058da204637c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/4853723
Reviewed-by: Erik Staab <estaab@chromium.org>
Commit-Queue: Egor Pasko <pasko@chromium.org>