Revert "BoringSSL: export all "finished" build artifacts for debugging."
This reverts commit 85cf177ff3505e507fedbfcf641dcd132da8b516.

Reason for revert:

  File "/b/s/w/ir/kitchen-checkout/build/recipes/recipes/boringssl.py", line 471, in RunSteps
    rel_path = src_path.piece_after(build_dir)
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Path' object has no attribute 'piece_after'

Failure Link: https://logs.chromium.org/logs/boringssl/buildbucket/cr-buildbucket/8674965479883128753/+/u/RECIPE_CRASH__Uncaught_exception_/logging

Original change's description:
> BoringSSL: export all "finished" build artifacts for debugging.
>
> This allows, among other things, figuring out symbol prefixing related
> errors, but also local analysis of the exact binaries that were run.
>
> Change-Id: I3e691ba9a2eba036e51096e03cdeae7c6a6a6964
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/8157203
> Reviewed-by: Adam Langley <agl@chromium.org>
> Commit-Queue: Rudolf Polzer <rpolzer@google.com>
> Auto-Submit: Rudolf Polzer <rpolzer@google.com>

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I0d328537cbb2a3d02423627071dc1233da7ba4df
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/8164082
Auto-Submit: Rudolf Polzer <rpolzer@google.com>
Reviewed-by: Xiangfei Ding <xfding@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Janek Zarzycki <janzarzycki@google.com>
Commit-Queue: Rudolf Polzer <rpolzer@google.com>