Revert "[fuzzing][coverage] Compute binary runtime dependencies with `gn`"
This reverts commit 26fe27580ecd7dc7036f007f1d974c60429e9fab.

Reason for revert: https://ci.chromium.org/ui/p/chromium/builders/ci/linux-centipede-fuzz-coverage/200/overview

> error: failed to load coverage: '/b/s/w/ir/cache/builder/src/out/657b-linux-centipede/phony/chrome/chrome': No such file or directory
> error: could not load coverage information

Original change's description:
> [fuzzing][coverage] Compute binary runtime dependencies with `gn`
>
> `*_fuzzer` binaries can invoke other binaries (mainly `*_unittests`). To
> generate coverage for the latter, `generate_coverage_metadata.py`
> currently passes every ELF in the build directory to `llvm-cov export`.
> This CL replaces that brute-force method with dependency queries to
> `gn`. This:
> * Avoids passing irrelevant binaries to `llvm-cov export` (e.g.,
>   `protoc` only used at build-time). This avoids especially large
>   perf penalties loading instrumented `chrome` unnecessarily.
> * Reuses `generate_coverage_metadata.py --binaries` to unify the
>   fuzz/non-fuzz code paths.
>
> This CL should not affect fuzz coverage functionality.
> https://crrev.com/c/6611702 inspired the approach.
>
> Bug: 416037384
> Test: https://ci.chromium.org/ui/p/chromium/builders/ci.shadow/linux-centipede-fuzz-coverage/17/overview
> Change-Id: I4f93ef212a32b9eb0b122d0f74eaf7d17287d15d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/6965958
> Reviewed-by: Garrett Beaty <gbeaty@google.com>
> Commit-Queue: Jonathan Lee <jonathanjlee@google.com>
> Reviewed-by: Titouan Rigoudy <titouan@chromium.org>

Bug: 416037384
Change-Id: Ice75f846ae11499774fcad2626a727ebe5428610
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/build/+/6976441
Auto-Submit: Jonathan Lee <jonathanjlee@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Garrett Beaty <gbeaty@google.com>
Commit-Queue: Jonathan Lee <jonathanjlee@google.com>